### ISSUE TITLE
Exception `albumName must not be null` for example app

### ISSUE THREAD

**Issue by qbait** [KasemJaffer/media_picker_builder#12]
I'm getting below exception on my real Pixel 2 Android Q. It works on Simulator and emulator though.

```
E/MethodChannel#media_picker_builder( 9399): Failed to handle method call
E/MethodChannel#media_picker_builder( 9399): java.lang.IllegalStateException: albumName must not be null
E/MethodChannel#media_picker_builder( 9399): 	at com.kasem.media_picker_builder.FileFetcher$Companion.getMediaFile(FileFetcher.kt:191)
E/MethodChannel#media_picker_builder( 9399): 	at com.kasem.media_picker_builder.FileFetcher$Companion.fetchImages(FileFetcher.kt:116)
E/MethodChannel#media_picker_builder( 9399): 	at com.kasem.media_picker_builder.FileFetcher$Companion.getAlbums(FileFetcher.kt:42)
E/MethodChannel#media_picker_builder( 9399): 	at com.kasem.media_picker_builder.MediaPickerBuilderPlugin.onMethodCall(MediaPickerBuilderPlugin.kt:36)
E/MethodChannel#media_picker_builder( 9399): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#media_picker_builder( 9399): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#media_picker_builder( 9399): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#media_picker_builder( 9399): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#media_picker_builder( 9399): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#media_picker_builder( 9399): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#media_picker_builder( 9399): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#media_picker_builder( 9399): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#media_picker_builder( 9399): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#media_picker_builder( 9399): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter ( 9399): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, albumName must not be null, null)
```

**Comment by anoopeashok** [comment]
Any solutions ?

**Comment by pedromarquesm** [comment]
this repo seems a bit abandoned to be honest

**Comment by Sauraus** [comment]
@KasemJaffer any input on this?
