### ISSUE TITLE
Error when loading media in IOS

### ISSUE THREAD

**Issue by EjazAmir** [KasemJaffer/media_picker_builder#17]
Hey, im using this package in my app, when i add the package it throws this error:
 
======== Exception caught by widgets library =======================================================
The following assertion was thrown building PickerWidget(dirty, state: PickerWidgetState#c1158):
'package:provider/src/listenable_provider.dart': Failed assertion: line 32 pos 16: 'create != null': is not true.

The relevant error-causing widget was: 
  PickerWidget file:///Users/apple/StudioProjects/teemates/lib/views/social/create_post_view.dart:517:16
When the exception was thrown, this was the stack: 
#2      new ListenableProvider (package:provider/src/listenable_provider.dart:32:16)
#3      new ChangeNotifierProvider (package:provider/src/change_notifier_provider.dart:110:8)
#4      PickerWidgetState._buildWidget (package:teemates/widgets/picker/picker_widget.dart:83:12)
#5      PickerWidgetState.build (package:teemates/widgets/picker/picker_widget.dart:55:11)
#6      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)

kindly anyone faced this issue,

**Comment by ramsmart-inno** [comment]
I am facing the issues mentioned below

`Xcode's output:
↳
    /Users/rammohan/Downloads/Flutter_Files/flutter/.pub-cache/hosted/pub.dartlang.org/media_picker_builder-1.3.2/ios/Classes/FileFetcher.swift:331:11: error: 'UIImageOrientation' has been renamed to 'UIImage.Orientation'
    extension UIImageOrientation{
              ^~~~~~~~~~~~~~~~~~
              UIImage.Orientation
    UIKit.UIImageOrientation:2:18: note: 'UIImageOrientation' was obsoleted in Swift 4.2
    public typealias UIImageOrientation = UIImage.Orientation
                     ^
    /Users/rammohan/Downloads/Flutter_Files/flutter/.pub-cache/hosted/pub.dartlang.org/media_picker_builder-1.3.2/ios/Classes/FileFetcher.swift:214:35: error: 'UIImagePNGRepresentation' has been replaced by instance method 'UIImage.pngData()'
                    if let imageRep = UIImagePNGRepresentation(image!) {
                                      ^~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~
                                      image!.pngData           
    UIKit.UIImagePNGRepresentation:2:13: note: 'UIImagePNGRepresentation' was obsoleted in Swift 3
    public func UIImagePNGRepresentation(_ image: UIImage) -> Data?
                ^
    /Users/rammohan/Downloads/Flutter_Files/flutter/.pub-cache/hosted/pub.dartlang.org/media_picker_builder-1.3.2/ios/Classes/FileFetcher.swift:333:9: warning: switch covers known cases, but 'UIImage.Orientation' may have additional unknown values, possibly added in future versions
            switch  self {
            ^
    /Users/rammohan/Downloads/Flutter_Files/flutter/.pub-cache/hosted/pub.dartlang.org/media_picker_builder-1.3.2/ios/Classes/FileFetcher.swift:333:9: note: handle unknown values using "@unknown default"
            switch  self {
            ^
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'video_player' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'permission_handler' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'media_picker_builder' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'media_gallery' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'image_picker' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'SVProgressHUD' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'Flutter' from project 'Pods')
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner editor. (in target 'Runner' from project 'Runner')

Could not build the application for the simulator.
Error launching application on iPhone 11.`

**Comment by ramsmart-inno** [comment]
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'video_player' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'permission_handler' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'media_picker_builder' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'media_gallery' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'image_picker' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'SVProgressHUD' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'Flutter' from project 'Pods')
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner editor. (in target 'Runner' from project 'Runner')
