### ISSUE TITLE
Unable to load asset: /storage/emulated/0/DCIM/.thumbnails/1579947777938.jpg

### ISSUE THREAD

**Issue by jpainam** [KasemJaffer/media_picker_builder#7]
Hi; there is an error loading the thumbnails
```dart
  Widget _buildImageContainer() {
    String thumbnailPath = mediaFile.thumbnailPath;
    if (thumbnailPath == null) {
      return FutureBuilder<String>(
        future: MediaPickerBuilder.getThumbnail(
            fileId: mediaFile.id, type: MediaType.IMAGE),
        builder: (BuildContext context, AsyncSnapshot<String> snapshot) {
          if (snapshot.hasData) {
            /*var updatedMediaFile = snapshot.data;
            mediaFile.thumbnailPath = updatedMediaFile.thumbnailPath;
            mediaFile.duration = updatedMediaFile.duration;
            mediaFile.mimeType = updatedMediaFile.mimeType;
            mediaFile.orientation = updatedMediaFile.orientation;*/
            thumbnailPath = snapshot.data;
            return _buildContainer(thumbnailPath);
          } else {
            return Loading();
          }
        },
      );
    } else {
      return _buildContainer(thumbnailPath);
    }
  }
```

**Comment by jpainam** [comment]
```dart
When the exception was thrown, this was the stack: 
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:484:44)
#2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:469:14)
#3      ImageProvider.resolve.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:327:17)
...
Image provider: AssetImage(bundle: null, name: "/storage/emulated/0/DCIM/.thumbnails/1579947777938.jpg")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#0d398(), name: "/storage/emulated/0/DCIM/.thumbnails/1579947777938.jpg", scale: 1.0)```
